sudo: false
language: node_js
dist: focal
node_js:
    - "19"
    - "18"
    - "16"
    - "14"
arch:
    - "amd64"
    - "arm64"
after_success:
    - "cat ./coverage/lcov.info | ./node_modules/.bin/coveralls"
